In [2]:
import numpy as np
x=np.array([1,22,23,5])
print(x)

[ 1 22 23  5]


In [3]:
y=[5,255,25,22,55]
print(y)

[5, 255, 25, 22, 55]


In [4]:
import numpy as np 
a=np.array([52,6,52,85,252])
print(a)
print(type(a))

[ 52   6  52  85 252]
<class 'numpy.ndarray'>


In [5]:
y=[5,255,25,22,55]
print(y)
print(type(y))

[5, 255, 25, 22, 55]
<class 'list'>


In [12]:
%timeit [j**4 for j in range(1,9)]

1.89 μs ± 27.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [14]:
import numpy as np
%timeit np.arange(1,9)**4

10.8 μs ± 93.8 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [15]:
import numpy as np
x=[1,2,5,520,52,5]
y=np.array(x)
print(y)

[  1   2   5 520  52   5]


In [16]:
import numpy as np
y=np.array([1,2,5,520,52,5])
print(y)

[  1   2   5 520  52   5]


In [17]:
import numpy as np
y=np.array([1,2,5,520,52,5])
y

array([  1,   2,   5, 520,  52,   5])

In [19]:
import numpy as np
x=[1,25,2,582]
y=np.array(x)
print(y)
print(type(x))
print(type(y))

[  1  25   2 582]
<class 'list'>
<class 'numpy.ndarray'>


In [22]:
l=[]
for i in range(1,5):
    int_1=input("Enter: ")
    l.append(int_1)
print(np.array(l))

Enter:  52
Enter:  12
Enter:  23
Enter:  223


['52' '12' '23' '223']


In [29]:
l=[]
for i in range(1,5):
    int_1=int(input("Enter: "))
    l.append(int_1)
print(np.array(l))
print(np.array(l).ndim)

Enter:  52
Enter:  52
Enter:  52
Enter:  52


[52 52 52 52]
1


In [24]:
import numpy as np
x=[52,85,963,965]
y=np.array(x)
print(y)
print(type(y))
print(y.ndim)

[ 52  85 963 965]
<class 'numpy.ndarray'>
1


In [31]:
arr2= np.array([[1,2,2],[1,255,5]])
print(arr2)
print(arr2.ndim)

[[  1   2   2]
 [  1 255   5]]
2


In [32]:
arr3 = np.array([[[1,2,5,5],[1,5,25,5],[52,53,52,98]]])
print(arr3)
print(arr3.ndim)

[[[ 1  2  5  5]
  [ 1  5 25  5]
  [52 53 52 98]]]
3


In [34]:
arrn=np.array([1,12,25,52,652],ndmin=10)
print(arrn)
print(arrn.ndim)

[[[[[[[[[[  1  12  25  52 652]]]]]]]]]]
10


In [35]:
ar_zero=np.zeros(4)
print(ar_zero)

[0. 0. 0. 0.]


In [39]:
ar_zero=np.zeros(5)
ar_zero1=np.zeros((3,5))
print(ar_zero)
print()
print(ar_zero1)

[0. 0. 0. 0. 0.]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [40]:
ar_one=np.ones(5)
print(ar_one)

[1. 1. 1. 1. 1.]


In [41]:
ar_em=np.empty(5)
print(ar_em)

[1. 1. 1. 1. 1.]


In [43]:
ar_rn=np.arange(5)
print(ar_rn)

[0 1 2 3 4]


In [44]:
ar_dia=np.eye(5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [45]:
ar_dia=np.eye(5,6)
print(ar_dia)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]


In [48]:
ar_lin=np.linspace(0,20,num=5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]


In [49]:
ar_lin=np.linspace(5,50,num=10)
print(ar_lin)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


RANDOM

In [50]:
import numpy as np
var=np.random.rand(5)
print(var)

[0.6121844  0.29052665 0.20407997 0.09345161 0.04684598]


In [52]:
var=np.random.rand(2,52)
print(var)

[[0.54126718 0.2310614  0.39382402 0.01818297 0.98643733 0.35720841
  0.55808671 0.2077749  0.87353804 0.50878799 0.66694767 0.04013823
  0.38131956 0.419979   0.07305624 0.19989597 0.07102871 0.03610851
  0.54466549 0.68109773 0.08241813 0.64819496 0.64442186 0.08040482
  0.48643553 0.83101655 0.40561099 0.81568733 0.54292332 0.14309516
  0.73311692 0.70113784 0.8869856  0.4998271  0.58280466 0.57635539
  0.89378982 0.34197507 0.43229429 0.33791649 0.26338255 0.17265612
  0.16925417 0.5015271  0.83423545 0.24785056 0.58539823 0.10836406
  0.63778669 0.67239146 0.37789559 0.409517  ]
 [0.0966597  0.14903638 0.15561629 0.54795143 0.67162882 0.76481524
  0.77564186 0.40831382 0.18777704 0.96177175 0.92771641 0.18822422
  0.50758647 0.07497613 0.00770854 0.74359527 0.88618063 0.9426363
  0.64772327 0.14264028 0.92434624 0.64701782 0.45811576 0.69629773
  0.07160752 0.91491952 0.57534675 0.06587477 0.84074929 0.7924593
  0.49434514 0.93315734 0.41065653 0.95960256 0.22304509 0.37753584
  0

In [53]:
var=np.random.randn(5)
print(var)

[-0.69143023  0.15992802 -0.51190556  1.08892387  1.57827686]


In [55]:
var=np.random.randn(2,52)
print(var)

[[-1.40259097 -0.57208982  1.04254759  1.33264122 -1.63472173  0.73325098
   0.70140732 -0.80263916  1.47408726  0.6414426  -1.70441194 -0.52546499
  -0.58604835  0.54479017 -0.51132689  1.02746714  1.73307724  1.0467861
  -0.27328715  1.3622933   0.08117391 -0.24047855 -2.23740327  0.95768022
  -0.7994203  -0.77591366 -0.77134363  1.50627079  1.24058    -1.73017109
  -2.16509823 -0.79667137 -2.10705212  0.37528788  0.62972687  0.57067902
  -0.1675934   1.18681084 -0.71661408 -0.60142383  0.29833281 -0.77642373
  -0.72093845  0.64337052 -0.36846129  0.41083671 -2.53951269  0.09399158
   0.83748442  1.67793575 -0.03208961 -1.44325473]
 [-0.74977682 -0.66038327 -0.61947466  0.32836462  0.07117103 -0.33267243
  -0.32746921 -0.6001987  -0.5603063   0.53714357  0.37255861 -0.06460132
   1.84299367 -0.07324958  1.93324751 -0.62942953  0.45201997  0.46019021
  -0.25470803 -0.19025636 -0.43266049 -0.44630835  1.38879882  0.29589495
   0.60974248  2.13934785  0.22003527 -0.19320529 -1.16205239 

In [57]:
var=np.random.ranf(8)
print(var)

[0.13842226 0.46070617 0.54157668 0.8034141  0.38103719 0.93133606
 0.01807679 0.19318731]


In [58]:
var=np.random.randint(2,10,50)
print(var)

[9 5 3 8 2 8 3 8 4 7 2 9 8 7 9 3 5 2 2 6 4 6 3 5 3 5 9 2 2 4 3 3 3 6 9 7 8
 3 3 9 9 9 3 9 8 7 8 4 2 5]


In [61]:
var=np.random.randint(8,50,85)
print(var)

[27 31 33 34 24 26  9 48 39 42 26 20 39 19 14 23 48 34 34 31 31 15 47 46
 49 11 18 15 19 44 49 31 20 46 41 13 37 15  8 20 49 46 12 24 17 48 30 48
 23 40  9 41 35 48 38 11 26 35  9 21 10 48 19 34 29 29 24 15 35 49 39 18
 24 40 17 28 21 14 32 19 44 31 18 23 11]


In [62]:
import numpy as np
var=np.array([1,5,2,55,6])
print("Data Type :",var.dtype)

Data Type : int64


In [63]:
var=np.array([1.5,5.5,5.6,6.5])
print("Data Type:",var.dtype)

Data Type: float64


In [64]:
var=np.array(["a","d","f","g"])
print("Data Type:",var.dtype)

Data Type: <U1


In [67]:
var=np.array(["f",52,"f"])
print("Data Type:",var.dtype)

Data Type: <U21


In [69]:
var=np.array([1,3,4,5,6],dtype=np.int8)
print("Data Type:",var.dtype)
print(var)

Data Type: int8
[1 3 4 5 6]


In [70]:
x=np.array([3,4,7,778,67],dtype="f")
print("Data Type:", x.dtype)
print(x)

Data Type: float32
[  3.   4.   7. 778.  67.]


In [74]:
x=np.array([2,35,656,24,65])
x1=np.float32(x)
print("Old Data Type:",x.dtype)
print("New Data Type:",x1.dtype)
print(x)
print()
print(x1)

Old Data Type: int64
New Data Type: float32
[  2  35 656  24  65]

[  2.  35. 656.  24.  65.]


In [75]:
x=np.array([2,4,43,545,23])
x1=np.float32(x)
x2=np.int_(x1)

print("Data Type of x :",x.dtype)
print("Data Type of x1:",x1.dtype)
print("Data Type of x2:",x2.dtype)

print(x)
print(x1)
print(x2)

Data Type of x : int64
Data Type of x1: float32
Data Type of x2: int64
[  2   4  43 545  23]
[  2.   4.  43. 545.  23.]
[  2   4  43 545  23]


In [76]:
x=np.array([1,434,213,23443,23])
x1=x.astype(float)
print(x)
print(x1)

[    1   434   213 23443    23]
[1.0000e+00 4.3400e+02 2.1300e+02 2.3443e+04 2.3000e+01]


ARITHMETIC OPERATION

In [78]:
import numpy as np
var=np.array([23,54,23,24,35,3])
var1=var+3
print(var1)

[26 57 26 27 38  6]


In [83]:
import numpy as np
var=np.array([23,54,23,24,35,3])
var1=var-3
print(var1)

[20 51 20 21 32  0]


In [84]:
import numpy as np
var=np.array([23,54,23,24,35,3])
var1=var*3
print(var1)

[ 69 162  69  72 105   9]


In [85]:
import numpy as np
var=np.array([23,54,23,24,35,3])
var1=var/3
print(var1)

[ 7.66666667 18.          7.66666667  8.         11.66666667  1.        ]


In [86]:
import numpy as np
var=np.array([23,54,23,24,35,3])
var1=var%3
print(var1)

[2 0 2 0 2 0]


In [87]:
import numpy as np
var=np.array([23,54,23,24,35,3])
var1=var**2
print(var1)

[ 529 2916  529  576 1225    9]


In [88]:
import numpy as np
var=np.array([23,54,23,24,35,3])
var1=1/var
print(var1)

[0.04347826 0.01851852 0.04347826 0.04166667 0.02857143 0.33333333]


In [81]:
var1=np.array([32,43,2,453,535,3])
var2=np.array([323,3546,234,33,324,423])
var3=var1+var2
print(var3)

[ 355 3589  236  486  859  426]


In [82]:
var1=np.array([32,43,2,453,535,3])
var2=np.array([323,3546,234,33,324,423])
var3=var2-var1
print(var3)

[ 291 3503  232 -420 -211  420]


In [89]:
var1=np.array([32,43,2,453,535,3])
var2=np.array([323,3546,234,33,324,423])
var3=var2*var1
print(var3)

[ 10336 152478    468  14949 173340   1269]


In [90]:
var1=np.array([32,43,2,453,535,3])
var2=np.array([323,3546,234,33,324,423])
var3=var2/var1
print(var3)

[1.00937500e+01 8.24651163e+01 1.17000000e+02 7.28476821e-02
 6.05607477e-01 1.41000000e+02]


In [91]:
var1=np.array([32,43,2,453,535,3])
var2=np.array([323,3546,234,33,324,423])
var3=var2%var1
print(var3)

[  3  20   0  33 324   0]


In [92]:
var1=np.array([32,43,2,453,535,3])
var2=np.array([323,3546,234,33,324,423])
var3=var2**var1
print(var3)

[-5309847598343653759  1707611926680305664                54756
  1962706618294788257                    0             75686967]


In [93]:
var1=np.array([[23,34,24,56],[24,56,87,24]])
var2=var1+3
print(var2)

[[26 37 27 59]
 [27 59 90 27]]


In [94]:
var1=np.array([[21,32,46,4,7,43],[24,45,76,24,45,224]])
var2=np.array([[23,32,43,24,232,535],[23,4,3,31,23,432]])
var3=var1+var2
print(var3)

[[ 44  64  89  28 239 578]
 [ 47  49  79  55  68 656]]


In [95]:
var1=np.array([[21,32,46,4,7,43],[24,45,76,24,45,224]])
var2=np.array([[23,32,43,24,232,535],[23,4,3,31,23,432]])
var3=var1+var2
print(var1)
print(var2)
print(var3)

[[ 21  32  46   4   7  43]
 [ 24  45  76  24  45 224]]
[[ 23  32  43  24 232 535]
 [ 23   4   3  31  23 432]]
[[ 44  64  89  28 239 578]
 [ 47  49  79  55  68 656]]


In [98]:
var=np.array([232,21,1,24424,42])
var1=np.reciprocal(var)
print(var1)

[0 0 1 0 0]


In [99]:
import numpy as np
var=np.array([23,323,4,13,24])
print("min:",np.min(var))
print("max:",np.max(var))

min: 4
max: 323


In [101]:
var=np.array([232,323,324,34,231,23,132])
print("min:",np.min(var),np.argmin(var))
print("max:",np.max(var),np.argmax(var))

min: 23 5
max: 324 2


In [103]:
var=np.array([[32,323,434],[534,432,43]])
print("min:",np.min(var,axis=0))

min: [ 32 323  43]


In [102]:
var=np.array([[32,323,434],[534,432,43]])
print("min",np.min(var,axis=0))

min [ 32 323  43]


In [104]:
var=np.array([[23,434,34,232],[32,34,2,55]])
print("min:",np.min(var,axis=1))

min: [23  2]


In [109]:
var=np.array([242,233,23,42132,32,24,64])
print("sqrt:",np.sqrt(var))

sqrt: [ 15.55634919  15.26433752   4.79583152 205.2608097    5.65685425
   4.89897949   8.        ]


In [108]:
var=np.array([34,245,53,41,543,35])
print("sine:",np.sin(var))
print("cosine:",np.cos(var))

sine: [ 0.52908269 -0.04421256  0.39592515 -0.15862267  0.47549715 -0.42818267]
cosine: [-0.84857027  0.99902215 -0.91828279 -0.98733928 -0.87971726 -0.90369221]


In [110]:
var=np.array([23,24,1,2,43,34])
print("cumsum:",np.cumsum(var))

cumsum: [ 23  47  48  50  93 127]


SHAPE

In [115]:
import numpy as np
var=np.array([[23,23],[1,31]])
print(var)
print()
print(var.shape)

[[23 23]
 [ 1 31]]

(2, 2)


In [117]:
var=np.array([[32,323,34,43,21],[233,22,4,23,23]])
print(var)
print(var.shape)

[[ 32 323  34  43  21]
 [233  22   4  23  23]]
(2, 5)


In [119]:
var=np.array([23,23,21,23],ndmin=10)
print(var)
print(var.ndim)
print(var.shape)

[[[[[[[[[[23 23 21 23]]]]]]]]]]
10
(1, 1, 1, 1, 1, 1, 1, 1, 1, 4)


In [121]:
var=np.array([23,23,434,122,32,32])
print(var)
var1=var.reshape(3,2)
print(var1)

[ 23  23 434 122  32  32]
[[ 23  23]
 [434 122]
 [ 32  32]]


In [123]:
var=np.array([23,434,42,1123,23,43,54,23])
print(var)
var1=var.reshape(4,2)
print(var1)
    

[  23  434   42 1123   23   43   54   23]
[[  23  434]
 [  42 1123]
 [  23   43]
 [  54   23]]


In [124]:
var=np.array([232,232,3,123,32,34])
print(var)
print(var.ndim)
var1=var.reshape(3,2)
print(var1)
print(var1.ndim)

[232 232   3 123  32  34]
1
[[232 232]
 [  3 123]
 [ 32  34]]
2


In [129]:
var=np.array([232,232,3,123,32,34,2,434,54,23,23,3])
print(var)
print(var.ndim)
var1=var.reshape(2,3,2)
print(var1)
print(var1.ndim)

[232 232   3 123  32  34   2 434  54  23  23   3]
1
[[[232 232]
  [  3 123]
  [ 32  34]]

 [[  2 434]
  [ 54  23]
  [ 23   3]]]
3


In [130]:
var=np.array([232,232,3,123,32,34,2,434,54,23,23,3])
print(var)
print(var.ndim)
var1=var.reshape(2,3,2)
print(var1)
print(var1.ndim)
print()
one=var1.reshape(-1)
print(one)
print(one.ndim)

[232 232   3 123  32  34   2 434  54  23  23   3]
1
[[[232 232]
  [  3 123]
  [ 32  34]]

 [[  2 434]
  [ 54  23]
  [ 23   3]]]
3

[232 232   3 123  32  34   2 434  54  23  23   3]
1


BROADCASTING

In [132]:
import numpy as np
var1=np.array([23,32,34])
print(var1.shape)
var2=np.array([[1],[2],[3]])
print(var2)
print(var1+var2)
print(var2.shape)

(3,)
[[1]
 [2]
 [3]]
[[24 33 35]
 [25 34 36]
 [26 35 37]]
(3, 1)


In [134]:
x=np.array([[23],[33]])
print(x)
print(x.shape)
x2=np.array([[1,23,43],[23,321,324]])
print(x2)
print(x2.shape)
print(x+x2)

[[23]
 [33]]
(2, 1)
[[  1  23  43]
 [ 23 321 324]]
(2, 3)
[[ 24  46  66]
 [ 56 354 357]]


INDEXING

In [136]:
import numpy as np
var=np.array([2,13,212,323,123,2,21,3])
print(var[6])

21


In [137]:
import numpy as np
var=np.array([2,13,212,323,123,2,21,3])
print(var[-6])

212


In [137]:
import numpy as np
var=np.array([2,13,212,323,123,2,21,3])
print(var[-6])

212


In [141]:
var=np.array([[23,43,231],[223,32,44]])
print(var)
print(var.ndim)
print()
print(var[1,2])

[[ 23  43 231]
 [223  32  44]]
2

44


In [144]:
var=np.array([[[3,22,3],[323,42,2],[2,33,23]]])
print(var)
print(var.ndim)
print(var[0,1,1])

[[[  3  22   3]
  [323  42   2]
  [  2  33  23]]]
3
42


SLICING

In [145]:
import numpy as np
var=np.array([3,23,44,43,43,45])
print(var)
print(var[1:3])

[ 3 23 44 43 43 45]
[23 44]


In [149]:
var=np.array([32,23,232,4,323,42,3])
print(var)
print(var[1:])
print(var[:3])
print(var[::3])
print(var[2:6:2])

[ 32  23 232   4 323  42   3]
[ 23 232   4 323  42   3]
[ 32  23 232]
[32  4  3]
[232 323]


In [151]:
var=np.array([[232,23,3,45,43],[34,54,3,53,34],[343,53,52,54,32]])
print(var)
print(var[1,1:])

[[232  23   3  45  43]
 [ 34  54   3  53  34]
 [343  53  52  54  32]]
[54  3 53 34]


ITERATION

In [152]:
import numpy as np
var=np.array([23,232,2,31,23,3,23])
print(var)
print()
for i in var:
    print(i)

[ 23 232   2  31  23   3  23]

23
232
2
31
23
3
23


In [155]:
var=np.array([[23,23,3,1,224,3],[23,3,22,23,23,23]])
for j in var:
    print(j)
print()
for i in var:
    for j in i:
        print(j)

[ 23  23   3   1 224   3]
[23  3 22 23 23 23]

23
23
3
1
224
3
23
3
22
23
23
23


In [158]:
var=np.array([[[32,23],[33,42],[23,43]]])
print(var)
print(var.ndim)
print()
for i in var:
    for j in i:
        for k in j:
            print(k)

[[[32 23]
  [33 42]
  [23 43]]]
3

32
23
33
42
23
43


In [159]:
var=np.array([[23,23,3,1,224,3],[23,3,22,23,23,23]])
print(var)
print(var.ndim)
print()
for i in np.nditer(var):
    print(i)

[[ 23  23   3   1 224   3]
 [ 23   3  22  23  23  23]]
2

23
23
3
1
224
3
23
3
22
23
23
23


In [160]:
var=np.array([[[32,23],[33,42],[23,43]]])
for i in np.nditer(var):
    print(i)

32
23
33
42
23
43


In [161]:
var=np.array([[[23,32],[32,42],[23,32]]])
print(var)
print(var.ndim)
for i in np.nditer(var,flags=['buffered'],op_dtypes=["S"]):
    print(i)

[[[23 32]
  [32 42]
  [23 32]]]
3
np.bytes_(b'23')
np.bytes_(b'32')
np.bytes_(b'32')
np.bytes_(b'42')
np.bytes_(b'23')
np.bytes_(b'32')


In [164]:
var=np.array([[[23,34],[23,234],[23,32]]])
print(var.ndim)
for i,d in np.ndenumerate(var):
    print(i,d)

3
(0, 0, 0) 23
(0, 0, 1) 34
(0, 1, 0) 23
(0, 1, 1) 234
(0, 2, 0) 23
(0, 2, 1) 32


COPY vs VIEW

In [166]:
import numpy as np
var=np.array([23,23,2,213,423])
co=var.copy()
print(var)
print(co)

[ 23  23   2 213 423]
[ 23  23   2 213 423]


In [167]:
var=np.array([23,23,2,213,423])
co=var.view()
print(var)
print(co)

[ 23  23   2 213 423]
[ 23  23   2 213 423]


In [170]:
var=np.array([23,23,2,213,423])
co=var.copy()
var[1]=454
print(var)
print(co)

[ 23 454   2 213 423]
[ 23  23   2 213 423]


In [169]:
var=np.array([23,23,2,213,423])
co=var.view()
var[1]=454
print(var)
print(co)

[ 23 454   2 213 423]
[ 23 454   2 213 423]


JOIN ARRAY

In [176]:
import numpy as np
var=np.array([23,3,34,23,43])
var2=np.array([23,23,32,4,234])
var3=np.concatenate((var,var2))
print(var3)

[ 23   3  34  23  43  23  23  32   4 234]


In [177]:
import numpy as np
var=np.array([23,3,34,23,43])
var2=np.array([23,23,32,4,234])
var3=np.concatenate((var,var2),axis=0)
print(var3)

[ 23   3  34  23  43  23  23  32   4 234]


In [183]:
var=np.array([[23,3],[23,43]])
var2=np.array([[23,23],[4,234]])
var3=np.concatenate((var,var2),axis=1)
print(var)
print(var2)
print(var3)

[[23  3]
 [23 43]]
[[ 23  23]
 [  4 234]]
[[ 23   3  23  23]
 [ 23  43   4 234]]


In [187]:
var=np.array([12,32,432,31,12])
var1=np.array([21,2,121,1,22])
var2=np.stack((var,var1),axis=1)
print(var2)

[[ 12  21]
 [ 32   2]
 [432 121]
 [ 31   1]
 [ 12  22]]


In [188]:
var=np.array([12,32,432,31,12])
var1=np.array([21,2,121,1,22])
var2=np.stack((var,var1),axis=0)
print(var2)

[[ 12  32 432  31  12]
 [ 21   2 121   1  22]]


In [190]:
var=np.array([12,32,432,31,12])
var1=np.array([21,2,121,1,22])
var2=np.hstack((var,var1))
print(var2)

[ 12  32 432  31  12  21   2 121   1  22]


In [191]:
var=np.array([12,32,432,31,12])
var1=np.array([21,2,121,1,22])
var2=np.vstack((var,var1))
print(var2)

[[ 12  32 432  31  12]
 [ 21   2 121   1  22]]


In [192]:
var=np.array([12,32,432,31,12])
var1=np.array([21,2,121,1,22])
var2=np.dstack((var,var1))
print(var2)

[[[ 12  21]
  [ 32   2]
  [432 121]
  [ 31   1]
  [ 12  22]]]


SPLIT ARRAY

In [194]:
import numpy as np
var=np.array([23,32,3,232,123,23,33])
print(var)
var2=np.array_split(var,3)
print(var2)

[ 23  32   3 232 123  23  33]
[array([23, 32,  3]), array([232, 123]), array([23, 33])]


In [195]:
import numpy as np
var=np.array([23,32,3,232,123,23,33])
print(var)
var2=np.array_split(var,3)
print(var2)
print(var2[0])

[ 23  32   3 232 123  23  33]
[array([23, 32,  3]), array([232, 123]), array([23, 33])]
[23 32  3]


In [199]:
import numpy as np
var=np.array([[23,32],[3,232],[123,23]])
print(var)
var2=np.array_split(var,3)
var3=np.array_split(var,3,axis=1)
print(var2)
print(var3)

[[ 23  32]
 [  3 232]
 [123  23]]
[array([[23, 32]]), array([[  3, 232]]), array([[123,  23]])]
[array([[ 23],
       [  3],
       [123]]), array([[ 32],
       [232],
       [ 23]]), array([], shape=(3, 0), dtype=int64)]


SEARCH

In [4]:
import numpy as np
var=np.array([1,23,4,9,4,22,33,21,32,2,2,3])
x=np.where(var==4)
print(x)

(array([2, 4]),)


In [7]:
var=np.array([21,3,2,23,13,12,323,42,42,4])
x=np.where((var%2)==0)
print(x)

(array([2, 5, 7, 8, 9]),)


In [6]:
var=np.array([21,3,2,23,13,12,323,42,42,4])
x=np.where(var/2==0)
print(x)

(array([], dtype=int64),)


In [8]:
var=np.array([1,2,3,6,7,8,9])
x=np.searchsorted(var,5)
print(x)

3


In [13]:
var=np.array([1,2,3,4,6,7,8,9,10,11,12,13])
x=np.searchsorted(var,5,side="right")
print(x)

4


In [14]:
var=np.array([1,2,3,7,8,9,10,11,12,13])
x=np.searchsorted(var,[4,5,6],side="right")
print(x)

[3 3 3]


SORT

In [15]:
var=np.array([2,3,12,42,11,3,3,1,5,13,24,5])
print(np.sort(var))

[ 1  2  3  3  3  5  5 11 12 13 24 42]


In [16]:
var=np.array(["g","a","f","e","b","c"])
print(np.sort(var))

['a' 'b' 'c' 'e' 'f' 'g']


In [18]:
var=np.array(["g","a","f","e","b","c"])
f=[True,True,False,False,False,True]
var1=var[f]
print(var1)
print(type(var1))

['g' 'a' 'c']
<class 'numpy.ndarray'>


In [21]:
var=np.array([1,2,4,5,3,63,23,])
np.random.shuffle(var)
print(var)

[ 1  3  4  2  5 63 23]


In [22]:
var=np.array([1,2,1,13,2,32,4,1,4,24,3])
x=np.unique(var)
print(x)

[ 1  2  3  4 13 24 32]


In [23]:
var=np.array([1,2,1,13,2,32,4,1,4,24,3])
x=np.unique(var,return_index=True)
print(x)

(array([ 1,  2,  3,  4, 13, 24, 32]), array([ 0,  1, 10,  6,  3,  9,  5]))


In [25]:
var=np.array([1,2,1,13,2,32,4,1,4,24,3])
x=np.unique(var,return_index=True,return_counts=True)
print(x)

(array([ 1,  2,  3,  4, 13, 24, 32]), array([ 0,  1, 10,  6,  3,  9,  5]), array([3, 2, 1, 2, 1, 1, 1]))


In [27]:
var=np.array([23,2,1,421,4213,2,22])
x=np.resize(var,(2,3))
print(x)

[[  23    2    1]
 [ 421 4213    2]]


In [29]:
var=np.array([23,2,1,421,4213,2,22])
x=np.resize(var,(3,4))
print(x)

[[  23    2    1  421]
 [4213    2   22   23]
 [   2    1  421 4213]]


In [30]:
var=np.array([12,21,4,3,32,23,123,42])
x=np.resize(var,(3,4))
print(x)
print(x.flatten())

[[ 12  21   4   3]
 [ 32  23 123  42]
 [ 12  21   4   3]]
[ 12  21   4   3  32  23 123  42  12  21   4   3]


In [31]:
var=np.array([12,21,4,3,32,23,123,42])
x=np.resize(var,(3,4))
print(x)
print(x.flatten(order="K"))

[[ 12  21   4   3]
 [ 32  23 123  42]
 [ 12  21   4   3]]
[ 12  21   4   3  32  23 123  42  12  21   4   3]


In [32]:
var=np.array([12,21,4,3,32,23,123,42])
x=np.resize(var,(3,4))
print(x)
print(x.flatten(order="F"))

[[ 12  21   4   3]
 [ 32  23 123  42]
 [ 12  21   4   3]]
[ 12  32  12  21  23  21   4 123   4   3  42   3]


In [33]:
var=np.array([12,21,4,3,32,23,123,42])
x=np.resize(var,(3,4))
print(x)
print(x.flatten(order="A"))

[[ 12  21   4   3]
 [ 32  23 123  42]
 [ 12  21   4   3]]
[ 12  21   4   3  32  23 123  42  12  21   4   3]


In [34]:
var=np.array([12,21,4,3,32,23,123,42])
x=np.resize(var,(3,4))
print(x)
print(x.flatten(order="C"))

[[ 12  21   4   3]
 [ 32  23 123  42]
 [ 12  21   4   3]]
[ 12  21   4   3  32  23 123  42  12  21   4   3]


In [35]:
var=np.array([12,21,4,3,32,23,123,42])
x=np.resize(var,(3,4))
print(x)
print(x.flatten(order="C"))
print(np.ravel(x,order="F"))

[[ 12  21   4   3]
 [ 32  23 123  42]
 [ 12  21   4   3]]
[ 12  21   4   3  32  23 123  42  12  21   4   3]
[ 12  32  12  21  23  21   4 123   4   3  42   3]


INSERT

In [37]:
import numpy as np
var=np.array([23,2,13,2,413,313,13])
x=np.insert(var,3,90)
print(x)          

[ 23   2  13  90   2 413 313  13]


In [38]:
import numpy as np
var=np.array([23,2,13,2,413,313,13])
x=np.insert(var,(2,5),90)
print(x)          

[ 23   2  90  13   2 413  90 313  13]


In [39]:
import numpy as np
var=np.array([23,2,13,2,413,313,13])
x=np.insert(var,(2,5),6.5)
print(x)          

[ 23   2   6  13   2 413   6 313  13]


In [47]:
import numpy as np
var=np.array([[23,2],[2,413],[313,13]])
x=np.insert(var,2,6.5,axis=0)
print(x)          

[[ 23   2]
 [  2 413]
 [  6   6]
 [313  13]]


In [48]:
import numpy as np
var=np.array([[23,2],[2,413],[313,13]])
x=np.insert(var,2,6.5,axis=1)
print(x)          

[[ 23   2   6]
 [  2 413   6]
 [313  13   6]]


In [58]:
import numpy as np
var=np.array([[23,2],[2,413],[313,13]])
x=np.insert(var,2,6.5,axis=1)
x1=np.append(var,6.5)
print(x) 
print(x1)

[[ 23   2   6]
 [  2 413   6]
 [313  13   6]]
[ 23.    2.    2.  413.  313.   13.    6.5]


In [50]:
import numpy as np
var=np.array([[23,2],[2,413],[313,13]])
x=np.insert(var,2,[34,64],axis=0)
print(x)          

[[ 23   2]
 [  2 413]
 [ 34  64]
 [313  13]]


In [54]:
import numpy as np
var=np.array([[23,2],[2,413],[313,13]])
x=np.insert(var,2,[34,64],axis=0)
x1=np.append(var,[[34,64]],axis=0)
print(x)        
print(x1)

[[ 23   2]
 [  2 413]
 [ 34  64]
 [313  13]]
[[ 23   2]
 [  2 413]
 [313  13]
 [ 34  64]]


Delete

In [60]:
var=np.array([23,131,32,23,23,15])
print(var)
x=np.delete(var,2)
print(x)

[ 23 131  32  23  23  15]
[ 23 131  23  23  15]


MATRIX

In [64]:
import numpy as np
var=np.matrix([[212,212,23],[12,41,4]])
print(var)
print(type(var))

[[212 212  23]
 [ 12  41   4]]
<class 'numpy.matrix'>


In [63]:
var=np.array([[212,212,23],[12,41,4]])
print(var)
print(type(var))

[[212 212  23]
 [ 12  41   4]]
<class 'numpy.ndarray'>


In [65]:
var=np.matrix([[212,212,23],[12,41,4]])
var1=np.matrix([[12,3,2],[23,42,13]])
print(var)
print(type(var))
print(var+var1)

[[212 212  23]
 [ 12  41   4]]
<class 'numpy.matrix'>
[[224 215  25]
 [ 35  83  17]]


In [66]:
var=np.matrix([[212,212,23],[12,41,4]])
var1=np.matrix([[12,3,2],[23,42,13]])
print(var)
print(type(var))
print(var-var1)

[[212 212  23]
 [ 12  41   4]]
<class 'numpy.matrix'>
[[200 209  21]
 [-11  -1  -9]]


In [70]:
var=np.matrix([[212,212],[12,41]])
var1=np.matrix([[12,3],[23,42]])
print(var)
print(type(var))
print(var*var1)
print()
print(var.dot(var1))

[[212 212]
 [ 12  41]]
<class 'numpy.matrix'>
[[7420 9540]
 [1087 1758]]

[[7420 9540]
 [1087 1758]]


In [71]:
var=np.matrix([[212,212,23],[12,41,4]])
print(var)
print(type(var))
print(np.transpose(var))

[[212 212  23]
 [ 12  41   4]]
<class 'numpy.matrix'>
[[212  12]
 [212  41]
 [ 23   4]]


In [72]:
var=np.matrix([[212,212,23],[12,41,4]])
print(var)
print(type(var))
print(np.transpose(var))
print()
print(var.T)

[[212 212  23]
 [ 12  41   4]]
<class 'numpy.matrix'>
[[212  12]
 [212  41]
 [ 23   4]]

[[212  12]
 [212  41]
 [ 23   4]]


In [73]:
var=np.matrix([[212,212,23],[12,41,4]])
print(var)
print(type(var))
print(np.transpose(var))
print()
print(var.T)
print()
print(np.swapaxes(var,0,1))

[[212 212  23]
 [ 12  41   4]]
<class 'numpy.matrix'>
[[212  12]
 [212  41]
 [ 23   4]]

[[212  12]
 [212  41]
 [ 23   4]]

[[212  12]
 [212  41]
 [ 23   4]]


In [77]:
var=np.matrix([[12,42,13],[23,42,13],[52,96,85]])
print(var.ndim)
print(var.shape)
print(np.linalg.inv(var))

2
(3, 3)
[[-9.09090909e-02  9.09090909e-02 -1.28102657e-17]
 [ 5.00743873e-02 -1.34680135e-02 -5.59862188e-03]
 [-9.39628847e-04 -4.04040404e-02  1.80878553e-02]]


In [80]:
var=np.matrix([[23,1],[23,31]])
print(var.shape)
print(np.linalg.matrix_power(var,3))

(2, 2)
[[13938  2226]
 [51198 31746]]


In [81]:
var=np.matrix([[23,1],[23,31]])
print(var.shape)
print(np.linalg.matrix_power(var,3))
print()
print(np.linalg.matrix_power(var,0))

(2, 2)
[[13938  2226]
 [51198 31746]]

[[1 0]
 [0 1]]


In [82]:
var=np.matrix([[23,1],[23,31]])
print(var.shape)
print(np.linalg.matrix_power(var,3))
print()
print(np.linalg.matrix_power(var,0))
print()
print(np.linalg.matrix_power(var,-2))

(2, 2)
[[13938  2226]
 [51198 31746]]

[[1 0]
 [0 1]]

[[ 0.00206679 -0.00011342]
 [-0.0026087   0.00115942]]


In [83]:
var=np.matrix([[23,1,4],[23,534,12],[34,23,55]])
print(var.shape)
print(np.linalg.det(var))

(3, 3)
597797.0000000012


In [84]:
var=np.matrix([[2,3],[32,2]])
print(var.shape)
print(np.linalg.det(var))

(2, 2)
-92.00000000000001
